name: 🐞 Bug Report
description: Report a problem or unexpected behavior in Ripely
title: "[Bug]"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📋 Bug Report for Ripely

  - type: input
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: e.g., App crashes when tapping the classify button
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: What actions lead to the bug?
      placeholder: |
        1. Go to '...'
        2. Tap on '...'
        3. See error '...'

  - type: input
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?

  - type: textarea
    id: media
    attributes:
      label: Screenshots / Video (if available)
      description: Drag and drop screenshots or screen recordings here.

  - type: input
    id: environment
    attributes:
      label: Device & Environment
      description: Provide info like device, iOS version, and Ripely version
      placeholder: e.g., iPhone 15, iOS 18.3.1, Ripely 1.0.0

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other relevant info about the bug.
